#!/usr/bin/env python3
"""Regenerates app/network/Shared/DeviceModelNames.swift from the
community-maintained apple-device-identifiers catalogs (MIT,
github.com/kyle-seongwoo-jun/apple-device-identifiers). The table maps
hardware identifiers (utsname.machine / sysctl hw.model, e.g. "iPhone17,2")
to retail names ("iPhone 16 Pro Max") for the concise device spec shown in
the network peers list. Unknown identifiers fall back to the identifier
itself at runtime.

Run from the repo (network required), then commit the regenerated file:
    python3 scripts/generate_device_model_names.py
"""

import json
import os
import urllib.request

CATALOGS = [
    "https://raw.githubusercontent.com/kyle-seongwoo-jun/apple-device-identifiers/main/ios-device-identifiers.json",
    "https://raw.githubusercontent.com/kyle-seongwoo-jun/apple-device-identifiers/main/mac-device-identifiers.json",
]
SWIFT_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "app", "network", "Shared", "DeviceModelNames.swift",
)

HEADER = '''//
//  DeviceModelNames.swift
//  URnetwork
//
//  generated by scripts/generate_device_model_names.py — do not edit by hand.
//  Maps hardware identifiers (utsname.machine on iOS, sysctl hw.model on
//  macOS) to retail device names for the device spec. Source catalogs:
//  github.com/kyle-seongwoo-jun/apple-device-identifiers (MIT).
//

import Foundation

enum DeviceModelNames {

    /// the retail name for a hardware identifier, e.g.
    /// "iPhone17,2" -> "iPhone 16 Pro Max". nil for unknown identifiers
    /// (newer devices than this table; the caller falls back to the
    /// identifier itself, which still beats the generic model)
    static func name(forIdentifier identifier: String) -> String? {
        return names[identifier]
    }

    private static let names: [String: String] = {
        var names = [String: String]()
        names.reserveCapacity(512)
        for line in table.split(separator: "\\n") {
            if let tab = line.firstIndex(of: "\\t") {
                names[String(line[..<tab])] = String(line[line.index(after: tab)...])
            }
        }
        return names
    }()

    private static let table = """
'''

FOOTER = '''"""
}
'''


def main():
    names = {}
    for url in CATALOGS:
        with urllib.request.urlopen(url, timeout=60) as response:
            catalog = json.load(response)
        for identifier, name in catalog.items():
            # some catalog values are lists of regional variants; take the first
            if isinstance(name, list):
                name = name[0]
            names.setdefault(identifier, name)

    lines = []
    for identifier in sorted(names):
        name = names[identifier]
        if "\t" in identifier or "\n" in identifier or "\n" in name or "\t" in name:
            continue
        lines.append(f"{identifier}\t{name}")

    with open(SWIFT_PATH, "w") as f:
        f.write(HEADER)
        f.write("\n".join(lines))
        f.write("\n")
        f.write(FOOTER)

    print(f"{len(lines)} identifiers -> {SWIFT_PATH}")


if __name__ == "__main__":
    main()
